---
- name: Update yum cache
  yum:
    name: '*'
    update_cache: yes 
  become: true

- name: Install required software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-devel
  become: true

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install the Python MySQLB module
  pip:
    name: MySQL-python
  become: true

- service:
    name: mysqld
    state: started

- name: MySQL | Remove the MySQL test database
  mysql_db:
    db: test
    state: absent
  become: true

- name: Set root password
  mysql_user:
    name: root
    password: "{{ task_mysql_password }}"
    host: localhost
  become: true

- template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
# tasks file for mysql
