---
- name: Update yum cache
  yum:
    name: '*'
    update_cache: yes 
  become: true

- name: Install required software
  yum:
    name: {{ item }}
    state: present
  with_items:
    - mysql-server
    - MySQL-python
  become: true

- name: Set rot password
  mysql_user: 
    name=root 
    password={{ task_mysql_password }} 
    host=localhost
  become: true

- name: MySQL | Remove the MySQL test database
  mysql_db:
    db=test
    state=absent
  become: true

- template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
# tasks file for mysql
