---
- name: Update yum cache
  yum:
    name: '*'
    update_cache: yes 
  become: true

- name: Install required software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-devel
  become: true

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install the Python MySQLB module
  pip:
    name: MySQL-python
  become: true

- service:
    name: mysqld
    state: started
    enabled: yes

- name: Set root password
  mysql_user:
    name: root
    password: "{{ task_mysql_password }}"
    host: "{{ item }}"
  become: true
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template:
    src: templates/root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: MySQL | Remove the MySQL test database
  mysql_db:
    db: test
    state: absent
  become: true

- name: Ensure the anonymous mysql user ""@{{ansible_hostname}} is deleted
  mysql_user:
    user: ""
    host: "{{ ansible_hostname }}"
    state: absent

- name: Ensure the anonymous mysql user ""@localhost is deleted
  mysql_user:
    user: ""
    state: absent

- template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
# tasks file for mysql
