---
- name: Update yum cache
  yum:
    update_cache=yes
    cache_valid_time=3600
  become: true

# Installing all necessary components
- name: Install required software
  yum:
    name={{ item }}
    state=present
  become: true
  with_items:
    - httpd

# Adding index.html to /var/www/html directory
- template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd

# tasks file for server
