---
- name: Update yum cache
  yum:
    name: '*'
    update_cache: yes
  become: true

- name: Install required software
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - php
    - php-mysql
# tasks file for server
